version: '3.9'
services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ffliq
      POSTGRES_USER: ffliq_user
      POSTGRES_PASSWORD: ffliq_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend/app:/app/app
      - ./backend/.env.example:/app/.env
    environment:
      DATABASE_URL: postgresql://ffliq_user:ffliq_pass@db:5432/ffliq
      SECRET_KEY: dev-secret-key
      DEBUG: "true"
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    depends_on:
      - backend

volumes:
  postgres_data:
